### ISSUE TITLE
Docker install instructions in README are outdated

### ISSUE THREAD

**Issue by MrConorAE** [ChuckTSI/starlink_dishy_grpc_web#1]
Hi there, and first of all, thanks for this project!
The Docker install instructions ("apt-get install docker") in README.md are outdated and don't work. The new instructions can be found on [this page](https://www.docker.com/products/docker-desktop) - perhaps it would be better to link here instead?

**Comment by ChuckTSI** [comment]
Thank you. I have updated the README and pointed the install of docker to the link you provided.

**Comment by MrConorAE** [comment]
Cool, thanks :)

-------- Original-Nachricht --------
